joint_limits:
  l_arm_shx:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm_elx:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm_wrx:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm_ely:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm_shy:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0
  l_arm_wry:
    has_velocity_limits: true
    max_velocity: 12
    has_acceleration_limits: false
    max_acceleration: 0